### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, watch 'D:\Test\'

### ISSUE THREAD

**Issue by BirdDev** [obsidianmd/obsidian-api#91]
Hi, I hope this is the correct issue backlog to report this issue.

I'm running obsidian, v1.0.3 on windows 11.
I am able to create and operate on vaults located on e.g. my desktop (C:\).
However, when trying to create or open a vault on a drive that is not 'C:\', I get the error shown mentioned in the title.

I am using cryptomator to securely store my files and wanted to create an obsidian vault inside of a cryptomator vault.
When opening or creating, said error occurrs.

Using the chrome debugging console, I could extract some more information which I hope will help:
```txt
app.js:1 Error: ENOENT: no such file or directory, unlink 'D:\Test\.OBSIDIANTEST'
    at Object.unlinkSync (node:original-fs:1718:3)
    at e.testInsensitive (app.js:1:1055558)
    at new e (app.js:1:1055260)
    at app.js:1:2155882
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
e @ app.js:1
app.js:1 Obsidian Developer Console
app.js:1 Error: EISDIR: illegal operation on a directory, watch 'D:\Test\'
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_uvException (node:internal/errors:521:10)
    at FSWatcher.<computed> (node:internal/original-fs/watchers:244:19)
    at Object.watch (node:original-fs:2247:34)
    at e.<anonymous> (app.js:1:1067103)
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
(anonymous) @ app.js:1
app.js:1 Error: EISDIR: illegal operation on a directory, watch 'D:\Test\'
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_uvException (node:internal/errors:521:10)
    at FSWatcher.<computed> (node:internal/original-fs/watchers:244:19)
    at Object.watch (node:original-fs:2247:34)
    at e.<anonymous> (app.js:1:1067103)
    at app.js:1:235201
    at Object.next (app.js:1:235306)
    at a (app.js:1:234045)
(anonymous) @ app.js:1
```

I should also note that the volume is mounted via 'webdav' which I guess is default for cryptomator and has worked for me well so far.

I am able to reproduce this issue, as well as on a second pc running windows 10 and cryptomator.
On my linux pc using the same cryptomator vault, everything works as expected.

Please let me know if I can provide you additional information.

Thank you very much!

**Comment by lishid** [comment]
This isn't the right place to report bugs - please head to https://forum.obsidian.md/

Also your bug will likely not be accepted since it's an issue with the emulated file system that cryptomator creates on Windows. Obsidian simply uses OS provided methods to interact with the file system and it seems that your cryptomator emulated file system does not behave in proper ways on Windows.

**Comment by lishid** [comment]
Feel free to ask for help on the forum - maybe someone has a workaround for you .
